### PR TITLE
implement module registry working

### PR DESCRIPTION
**Pull request by rkdud007**
This pull request addresses the logic for making the module registry functional. It includes the following:

- Accessing Sierra via a provided class_hash.
- Converting the accessed Sierra data into a contract_class.
- Serializing the contract_class into the input.json format that the preprocessor expects.

### CODE REVIEW

**Comment by rkdud007** [comment]
can you final check if file format is expected on cairo side? @Okm165
: https://github.com/HerodotusDev/hdp/blob/feat/module-registry/crates/core-new/input.json

**Comment by Okm165** [comment]
> can you final check if file format is expected on cairo side? @Okm165 : https://github.com/HerodotusDev/hdp/blob/feat/module-registry/crates/core-new/input.json

`module` is valid
`module_class` follows `CasmContractClass` object, it is valid

**Comment by Okm165** [comment]
U can incorporate this crate https://github.com/tokio-rs/tracing to have nice `debug`/`tracing` logs when the instance will run in docker later.

**Comment by Okm165** [comment]
only one of `license` or `license-file` is necessary in cargo workspace

**Review by Okm165 — APPROVED** [review]
LGTM

**Pull request merged**
